services:
  refinery:
    image: ghcr.io/zoranner/refinery:0.1.1
    container_name: refinery
    restart: always
    env_file:
      - ./.env
    depends_on:
      - reader
      - searxng
    ports:
      - 18090:8080
  reader:
    image: ghcr.io/jina-ai/reader:oss
    container_name: refinery-reader
    restart: always
  searxng:
    image: searxng/searxng:latest
    container_name: refinery-searxng
    restart: always
    environment:
      - SEARXNG_BIND_ADDRESS=0.0.0.0
      - SEARXNG_PORT=8888
      - SEARXNG_SETTINGS_FILE=/etc/searxng/settings.yml
    volumes:
      - ./app/limiter.toml:/etc/searxng/limiter.toml:ro
      - ./app/settings.yml:/etc/searxng/settings.yml:ro
networks:
  default:
    external: true
    name: refinery
